Cookbook/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from recipes.views import home, search_results, search, autocompleteModel
from chef.views import SignUp

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('recipes/', include('recipes.urls')),
    path('login/', LoginView.as_view(template_name="Cookbook/login_form.html"), name="player_login"),
    path('logout/', LogoutView.as_view(), name="player_logout"),
    path('signup/', SignUp.as_view(), name="signup"),
    path('search_results/', search_results, name="search_results"),
    path('test_search_results/', search, name='search'),
    path('ajax_calls/search/<str:field>', autocompleteModel),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'recipes'
urlpatterns = [
    path('show_recipe/<int:recipe>', views.show_recipe, name='show_recipe'),
    path('new_data/', views.new_recipe, name='new_data'),
    path('data_from_url/', views.new_from_url, name='data_from_url'),
    path('remove_recipe/<int:recipe>/', views.remove_recipe, name='remove_recipe'),
    path('edit_recipe/<int:recipe>/', views.edit_recipe, name='edit_recipe'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/models.py
from django.db import models


# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    # author = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    difficulty = models.CharField(max_length=50, blank=True)
    time = models.CharField(max_length=50, blank=True)
    portions = models.CharField(max_length=50, blank=True)
    categories = models.ManyToManyField(Category, blank=True)
    ingredients = models.ManyToManyField(Ingredient)
    date = models.DateField(auto_now_add=True)
    website = models.CharField(max_length=200, blank=True)
    picture = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.name

    def get_json(self):
        json = {}
        for item in Recipe._meta.fields:
            # if item.name == "picture":
            #     json["picture"] = self.picture.name
            #     continue
            json[item.name] = getattr(self, item.name)

        ingredients = Ingredient.objects.filter(recipe=self)
        quantities = Quantity.objects.filter(recipe_id=json["id"])
        groups = {item.set for item in quantities}
        categories = self.categories.values_list().order_by("name")
        if categories.exists():
            json["categories"] = [category[1] for category in categories]

        json["ingredients"] = {}
        for group in groups:
            values = quantities.filter(set=group)
            keys = [ingredients.get(quantity=value) for value in values]
            json["ingredients"][group] = {key.name: value.quantity for key, value in zip(keys, values)}
        procedures = Procedure.objects.filter(recipe=self)
        json["recipe"] = {procedure.name: procedure.procedure for procedure in procedures}
        return json

    def get_absolute_url(self):
        return reverse('recipes:show_recipe', args=[self.id])


class Quantity(models.Model):
    ingredient = models.ForeignKey(Ingredient,
                                   on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe,
                               on_delete=models.CASCADE)
    set = models.CharField(max_length=100, blank=True)
    quantity = models.CharField(max_length=100, blank=True)


class Procedure(models.Model):
    name = models.CharField(max_length=50)
    procedure = models.TextField()
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    def __str__(self):
        return "{}: {}".format(self.recipe, self.name)

recipes/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, widgets, IntegerField
from django import forms
from recipes.models import Recipe, Procedure, Category, Ingredient


class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        exclude = ('date', 'author', 'ingredients', 'categories')


class RecipeURLForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ['website']

recipes/views.py
import json

import requests
from django.contrib.auth.decorators import login_required
from django.core.files import File
from django.core.files.temp import NamedTemporaryFile
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader

import recipes.URL_parser as URL_parser

# Create your views here.
from recipes.forms import RecipeForm, RecipeURLForm
from recipes.models import Recipe, Procedure, Ingredient, Quantity, Category


# def welcome(request):
#     my_recipes = Recipe.objects.filter(author=request.user)
#     return render(request, "Cookbook/welcome.html", {'my_recipes': my_recipes})


@login_required
def home(request):
    my_recipes = Recipe.objects.filter(author=request.user)
    categories = Category.objects.all()
    context = {"my_recipes": my_recipes, "categories": categories}

    return render(request, "Cookbook/home.html", context)


@login_required
def search(request):
  query = request.POST['name']
  t = loader.get_template('Cookbook/home.html')
  c ={'query': query}
  return HttpResponse(t.render(c))


def autocompleteModel(request, field):
    if request.is_ajax():
        q = request.GET.get('term', '').capitalize()
        if field == "recipe":
            search_qs = Recipe.objects.filter(name__icontains=q)
        else:
            search_qs = Ingredient.objects.filter(name__icontains=q)
        results = []
        for r in search_qs:
            results.append(r.name)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

@login_required
def search_results(request):
    if request.method == 'POST':
        if request.POST["type"] == 'ingredient':
            my_recipes = Recipe.objects.filter(author=request.user, ingredients__name__contains=request.POST["name"])
        elif request.POST["type"] == 'category':
            my_recipes = Recipe.objects.filter(author=request.user, categories__name=request.POST["name"])
        else:
            my_recipes = Recipe.objects.filter(author=request.user, name__contains=request.POST['name'])
        my_recipes = set(my_recipes)
    else:
        my_recipes = Recipe.objects.filter(author=request.user)
    categories = Category.objects.all().order_by("name")
    context = {"my_recipes": my_recipes, "categories": categories}
    return render(request, "Cookbook/home.html", context)


@login_required
def show_recipe(request, recipe):
    record = Recipe.objects.get(id=recipe)
    record = record.get_json()
    return render(request, 'recipes/show_recipe.html', record)

@login_required
def remove_recipe(request, recipe):
    item = Recipe.objects.get(id=recipe)
    item.delete()

    my_recipes = Recipe.objects.filter(author=request.user)
    categories = Category.objects.all()
    context = {"my_recipes": my_recipes, "categories": categories}

    return render(request, "Cookbook/home.html", context)

@login_required
def new_recipe(request):
    if request.method == "POST":
        recipe = Recipe()
        form = RecipeForm(request.POST, request.FILES, instance=recipe)

        if form.is_valid():
            complete_form = form.save(commit=False)
            complete_form.author = request.user.get_username()
            result = dict(form.data)
            complete_form.save()

            for ingredient, quantity, group in zip(result["ingredient"], result["quantity"], result["group"]):
                if ingredient != '':
                    new_ingredient = Ingredient.objects.get_or_create(name=ingredient)
                    complete_form.ingredients.add(new_ingredient[0].pk)
                    Quantity.objects.get_or_create(ingredient=new_ingredient[0], recipe=complete_form, quantity=quantity, set=group)

            for step, text in zip(result["step"], result["text"]):
                if step != '' and text != '':
                    Procedure.objects.get_or_create(recipe=complete_form, name=step, procedure=text)

            for category in result["category"]:
                if category != '':
                    new_category = Category.objects.get_or_create(name=category)
                    complete_form.categories.add(new_category[0].pk)

            form.save_m2m()

            return redirect('home')
    else:
        form = RecipeForm()
    return render(request, "recipes/dynamic_recipe.html", {'form': form})



@login_required
def edit_recipe(request, recipe):
    instance = get_object_or_404(Recipe, id=recipe)
    form = RecipeForm(request.POST or None, instance=instance)
    procedure = Procedure.objects.filter(recipe=instance)
    categories = Category.objects.filter(recipe=instance)
    quantities = Quantity.objects.filter(recipe=instance)
    ingredients_list = [{"id": quantity.ingredient.id, "name": quantity.ingredient.name, "quantity": quantity.quantity,
                         "set": quantity.set} for quantity in quantities]

    context = {'form': form,
               'recipe': instance, 'procedure': procedure, 'categories': categories, 'ingredients': ingredients_list}

    if form.is_valid():
        complete_form = form.save(commit=False)
        complete_form.author = request.user.get_username()
        result = dict(form.data)

        ingredient_set = zip(result["ingredient"], result["quantity"], result["group"])
        print(complete_form.ingredients)

        for item in Quantity.objects.filter(recipe=instance):
            if zip(item.ingredient.name, item.quantity, item.set) not in ingredient_set:
                item.delete()

        for item in Procedure.objects.filter(recipe=instance):
            if item.name not in result["step"]:
                item.delete()

        items = Ingredient.objects.filter(recipe=instance)
        for item in items:
            recipes = [Recipe.objects.filter(ingredients__name=item)]
            if len(recipes[0]) <= 1:
                if item.name not in result["ingredient"]:
                    item.delete()

        instance.ingredients.clear()
        instance.categories.clear()

        complete_form.save()

        for ingredient, quantity, group in zip(result["ingredient"], result["quantity"], result["group"]):
            if ingredient != '':
                new_ingredient = Ingredient.objects.get_or_create(name=ingredient)
                complete_form.ingredients.add(new_ingredient[0].pk)
                if group == '':
                    group = 'general'
                Quantity.objects.get_or_create(ingredient=new_ingredient[0], recipe=complete_form,
                                               # quantity=quantity, set=group)
                                               defaults={'quantity': quantity, 'set': group})

        for step, text in zip(result["step"], result["text"]):
            if step != '' and text != '':
                Procedure.objects.get_or_create(recipe=complete_form, name=step, procedure=text)

        instance.categories.clear()
        for category in result["category"]:
            if category != '':
                new_category = Category.objects.get_or_create(name=category)
                complete_form.categories.add(new_category[0].pk)

        form.save_m2m()

        return redirect('home')
    return render(request, "recipes/dynamic_recipe.html", context)

@login_required
def new_from_url(request):
    if request.method == "POST":
        recipe = Recipe()
        form = RecipeURLForm(instance=recipe, data=request.POST)
        if form.is_valid():
            complete_form = form.save(commit=False)
            if complete_form.website.find("apetitonline") >= 0:
                record = URL_parser.ApetitRecord(complete_form.website)
            elif complete_form.website.find("varecha") >= 0:
                record = URL_parser.VarechaRecord(complete_form.website)
            else:
                record = URL_parser.DobruchutRecord(complete_form.website)
            complete_form.author = request.user.get_username()
            record.scrape_data()

            for key, value in record.record.items():
                if key != "ingredients" and key != "recipe" and key != "image":
                    setattr(complete_form, key, value)
                elif key == "image":
                    img_temp = NamedTemporaryFile(delete=True)
                    img_temp.write(requests.get(value).content)
                    img_temp.flush()

                    complete_form.picture.save(record.record["name"].replace(u' ', u'_')+".jpg", File(img_temp))
            complete_form.save()


            # new_recipe = Recipe(website=recipe.website, name=record.record["name"])
            for group, items in record.record["ingredients"].items():
                for item, quantity in items.items():
                    new_ingredient = Ingredient.objects.get_or_create(name=item)
                    complete_form.ingredients.add(new_ingredient[0].pk)
                    Quantity.objects.get_or_create(ingredient=new_ingredient[0], recipe=complete_form, quantity=quantity, set=group)

            for name, step in record.record["recipe"].items():
                Procedure.objects.get_or_create(recipe=complete_form, name=name, procedure=step)

            form.save_m2m()
            return redirect('home')
    else:
        form = RecipeURLForm()
    return render(request, "recipes/url_form.html", {'form': form})

templates/recipes/categories_list.html
{#<div style="width: 100%; text-align: center;">#}
{% for category in categories_list %}

        <div style="display: inline-block; margin-bottom: 5px">
        <form  action="{% url 'search_results' %}" method='post'>
            {% csrf_token %}
                <input type="hidden" value="{{ category }}" name="name">
                <input type="hidden" value="category" name="type">
                <button class="list-group-item list-group-item-warning" type="submit">           {# {{ recipe.get_absolute_url }} #}
                    {{ category }}
                </button>
        </form>
        </div>
{% endfor %}
{#</div>#}

templates/recipes/dynamic_recipe.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

{% extends "Cookbook/base.html" %}

{% load crispy_forms_tags %}

{% block title %}
     {{ name }}     {#    Home: {{ user.username }}#}
{% endblock %}

{% block content %}

{% if recipe %}
<form enctype="multipart/form-data" method="POST" role="form" action="{% url 'recipes:edit_recipe' recipe=recipe.id %}">
{% else %}
<form enctype="multipart/form-data" method="POST" role="form" action="{% url 'recipes:new_data' %}">
{% endif %}

  <div class="row">
    <div class="col-md-6 mb-3">
        {{ form.name|as_crispy_field }}
    </div>

    <div class="col-md-6 mb-3">
        {{ form.website|as_crispy_field }}
    </div>
  </div>
    <br>

  <div class="row">
    <div class="col-md-4 mb-3">
        {{ form.difficulty|as_crispy_field }}
    </div>
    <div class="col-md-4 mb-3">
        {{ form.portions|as_crispy_field }}
    </div>
    <div class="col-md-4 mb-3">
        {{ form.time|as_crispy_field }}
    </div>
  </div>
  <br>

  <label for="ingredient_fields">Ingredients</label>
  <div class="row">
    <div class="col-sm-4 nopadding">
      <div class="form-group">
          {% if ingredients and ingredients.0.set != "general" %}
              <input type="text" class="form-control" id="group" name="group" value="{{ ingredients.0.set }}" placeholder="Group">
          {% else %}
              <input type="text" class="form-control" id="group" name="group" value="" placeholder="Group">
          {% endif %}
      </div>
    </div>
    <div class="col-sm-4 nopadding">
      <div class="form-group">
          {% if ingredients %}
              <input type="text" class="form-control" id="ingredient" name="ingredient" value="{{ ingredients.0.name }}" placeholder="Ingredient">
          {% else %}
              <input type="text" class="form-control" id="ingredient" name="ingredient" value="" placeholder="Ingredient">
          {% endif %}
      </div>
    </div>
    <div class="col-sm-4 nopadding">
      <div class="form-group">
        <div class="input-group">
          {% if ingredients %}
              <input type="text" class="form-control" id="quantity" name="quantity" value="{{ ingredients.0.quantity }}" placeholder="Quantity">
          {% else %}
              <input type="text" class="form-control" id="quantity" name="quantity" value="" placeholder="Quantity">
          {% endif %}
          <div class="input-group-btn">
            <button class="btn btn-success" id="ingredient_button" type="button"  onclick="ingredient_fields('','','');"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> </button>
          </div>
        </div>

      </div>
    </div>
    <div id="ingredient_fields"></div>
    <div class="clear"></div>
  </div>
  <br>
  <script>
    {% for ingredient in ingredients %}
        {% if ingredient.id != ingredients.0.id %}
            ingredient_fields("{{ ingredient.set }}", "{{ ingredient.name }}", "{{ ingredient.quantity }}");
        {% endif %}
    {% endfor %}
  </script>


  <label for="procedure_fields">Procedure</label>
  <div class="row">
    <div class="col-sm-2 nopadding">
      <div class="form-group">
          {% if procedure %}
              <input type="text" class="form-control" id="step" name="step" value="{{ procedure.0.name }}" placeholder="Name of step">
          {% else %}
              <input type="text" class="form-control" id="step" name="step" value="" placeholder="Name of step">
          {% endif %}
      </div>
    </div>
    <div class="col-sm-10 nopadding">
      <div class="form-group">
        <div class="input-group">
            {% if procedure %}
              <textarea class="form-control" rows="3" id="text" name="text" placeholder="Procedure">{{ procedure.0.procedure }}</textarea>
            {% else %}
              <textarea class="form-control" rows="3" id="text" name="text" placeholder="Procedure"></textarea>
            {% endif %}
          <div class="input-group-btn">
            <button class="btn btn-success" id="procedure_button" type="button"  onclick="procedure_fields('','');"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> </button>
          </div>
        </div>

      </div>
    </div>
    <div id="procedure_fields"></div>
    <div class="clear"></div>
  </div>
  <br>
  <script>
    {% for step in procedure %}
        {% if step.id != procedure.0.id %}
            procedure_fields("{{ step.name }}", "{{ step.procedure }}");
        {% endif %}
    {% endfor %}
  </script>



  <label for="category_fields">Categories</label>
  <div class="row">
    <div class="col-sm-12 nopadding">
      <div class="form-group">
        <div class="input-group">
                {% if categories %}
                    <input type="text" class="form-control" id="category" name="category" value="{{categories.0.name}}" placeholder="Name of category">
                {% else %}
                    <input type="text" class="form-control" id="category" name="category" value="" placeholder="Name of category">
                {% endif %}
                <div class="input-group-btn">
                    <button class="btn btn-success" id="category_button" type="button"  onclick="category_fields('')"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> </button>
                </div>
        </div>


      </div>
    </div>
    <div id="category_fields"></div>
    <div class="clear"></div>
  </div>
  <br>

  <script>
    {% for category in categories %}
        {% if category.id != categories.0.id %}
            category_fields("{{ category.name }}");
        {% endif %}
    {% endfor %}
  </script>





  <div class="row">
      <div class="col-md-3 mb-3">
        {{ form.picture|as_crispy_field }}
      </div>
  </div>
    <br>


    {% csrf_token %}

  <button class="btn btn-primary" type="submit" value="">Submit form</button>
</form>







{% endblock %}

templates/recipes/ingredients_list.html
{% if ingredients_list %}

    <table style="width:100%">
        <col width="20%">
        <col width="80%">
        {% for ingredient, quantity in ingredients_list.items %}
            <tr>
                <td>{{ quantity }}</td>
                <td>

                    <form  action="{% url 'search_results' %}" method='post'>
                        {% csrf_token %}
{#                        <div class="input-group" style="padding: 10px; margin: 0 auto;">#}
                            <input type="hidden" value="{{ ingredient }}" name="name">
                            <input type="hidden" value="ingredient" name="type">
                            <button class="list-group-item list-group-item-warning" type="submit" style="display: block; width: 100%">           {# {{ recipe.get_absolute_url }} #}
                                {{ ingredient }}
                            </button>
{#                        </div>#}
                    </form>

                </td>
            </tr>
        {% endfor %}
    </table>

{% endif %}

templates/recipes/recipe_form.html
{% extends "Cookbook/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    New Recipe
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'recipes:new_data' %}">
        {{ form | crispy }}

        {% csrf_token %}
        <button type="submit">Add procedure</button>
    </form>
{% endblock %}

templates/recipes/recipe_list_snippet.html
{% if recipes_list %}

    <div class="list-group bg-info">
        {% for recipe in recipes_list %}
            <a class="list-group-item list-group-item-info" href="{{ recipe.get_absolute_url }}">
                {{ recipe }}
{#                <div style="text-align: right">#}
                    <img src="{{MEDIA_URL}}{{recipe.picture.url}}" alt="Image of recipe is not present" style="margin-left: auto; margin-top: -20px; display: block; height: 100px">
{#                </div>#}
            </a>
        {% endfor %}
    </div>

{% endif %}

templates/recipes/show_recipe.html
{% extends "Cookbook/base.html" %}

{% block navbar %}
    <li><a href="{% url 'recipes:remove_recipe' recipe=id %}" style="margin-right: 20px">
        Delete <span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></li>
    <li><a href="{% url 'recipes:edit_recipe' recipe=id %}" style="margin-right: 20px">
        Edit <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></li>
{% endblock %}

{% block title %}
     {{ name }}     {#    Home: {{ user.username }}#}
{% endblock %}

{% block content %}
    <h1 class="section-title">{{ name }}</h1>     {#    <h2 class="text-primary">Welcome, {{ user.username }}</h2>#}

    <div class="row">
        <div class="col-md-4">
            <br>
            <h3 class="info-title">Difficulty</h3>
            {% if difficulty %}
                <p>{{ difficulty }}</p>
            {% else %}
                <p>Difficulty was not specified.</p>
            {% endif %}

            <br>
            <h3 class="info-title">Portions</h3>
            {% if portions %}
                <p>{{ portions }}</p>
            {% else %}
                <p>Number of portions was not specified.</p>
            {% endif %}

            <br>
            <h3 class="info-title">Time</h3>
            {% if time %}
                <p>{{ time }}</p>
            {% else %}
                <p>Total time was not specified.</p>
            {% endif %}
            <br>

        </div>

        <div class="col-md-8">
            <img src="{{MEDIA_URL}}{{picture.url}}" alt="Image of recipe is not present" style="margin: auto; display: block; height: 338px">
        </div>
    </div>

    {% if categories %}
    <br>
    <div class="row">
        <h4>Categories: </h4>
            {% include "recipes/categories_list.html" with categories_list=categories %}
{#        {% for category in categories %}#}
{#            {% include "recipes/categories_list.html" with categories_list=category %}#}
{#        {% endfor %}#}
    </div>
    {% endif %}

    <br>
    <div class="row">
        <div class="col-md-4">
            <h3 class="section-title">Ingredients</h3>
            <div style="border-style: solid; padding: 10px; background: ivory; border-radius: 20px">

                {% if ingredients.general %}
                        <br>
                        {% include "recipes/ingredients_list.html" with ingredients_list=ingredients.general %}
                {% endif %}
                {% for group, ingredients in ingredients.items %}
                    {% if group != "general"%}
                        <br>
                        <strong>{{ group }}</strong>
                        {% include "recipes/ingredients_list.html" with ingredients_list=ingredients %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>

        <h3 class="section-title">Procedure</h3>
        <div class="col-md-8">

            {% for step, procedure in recipe.items %}
                <strong><h4 style="color: red">{{ step }}</h4></strong>
                <p>{{ procedure }}</p>
            {% endfor %}
        </div>

    </div>
    </div>

{% endblock %}

templates/recipes/url_form.html
{% extends "Cookbook/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    New Recipe
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'recipes:data_from_url' %}">
        {{ form | crispy }}

        {% csrf_token %}
        <button type="submit">Create Recipe</button>
    </form>
{% endblock %}